services:
  postgres-db:
    image: postgres:14-alpine
    container_name: jobapp-db
    environment:
      POSTGRES_DB: job_application_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: jobapp-backend
    ports:
      - "8080:8080"
    environment:
      # Injecting environment variables into the Spring Boot container
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/job_application_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_JWT_SECRET: ${APP_JWT_SECRET:-ProductionReadySecretKeyMustBeSetInEnvironmentVariables}
    depends_on:
      postgres-db:
        condition: service_healthy